import SearchFilterBar from "@/Components/BrowseRoom/SearchFilterBar";
import ListingCard from "@/Components/ListingCard";
import { Navbar } from "@/Components/Navbar";

export default function BrowseRoom() {
    // Dummy data for listings
    const dummyListings = [
        {
            id: 1,
            image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "MASTER ROOM",
            price: "RM 850/mo",
            title: "Sunway Geo Residences",
            location: "Bandar Sunway, Selangor",
            tags: ["Quiet", "PetFriendly", "NonSmoker", "Wifi", "AC"],
            beds: "1",
            baths: "1 Bath",
            size: "650",
            amenities: ["wifi", "ac", "parking", "gym", "pool"],
            rating: 4.8,
            reviews: 24,
            distance: "1.2 km from Sunway University",
            availableFrom: "Jan 15, 2024",
            isVerified: true,
            isFeatured: true,
            views: 245,
            saved: 42,
            postedDate: "2 hours ago",
            propertyType: "Condominium",
            floor: "12th Floor",
            furnished: "Fully Furnished",
            leaseDuration: "12 months",
            deposit: "2 months",
            utilities: "Included",
            petPolicy: "Allowed",
            smoking: "Not Allowed",
            genderPreference: "Mixed",
            roommateCount: "3",
            availableSpots: "1",
            contactPerson: "Mr. Lim",
            contactNumber: "+6012-345 6789",
            whatsappAvailable: true,
        },
        {
            id: 2,
            image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "SINGLE ROOM",
            price: "RM 600/mo",
            title: "Nadi Bangsar Service Residence",
            location: "Bangsar, Kuala Lumpur",
            tags: ["NearLRT", "Professional", "Gym", "Pool", "Security"],
            beds: "1",
            baths: "Shared",
            size: "450",
            amenities: ["wifi", "gym", "pool", "security", "laundry"],
            rating: 4.6,
            reviews: 18,
            distance: "300m from Bangsar LRT",
            availableFrom: "Immediate",
            isVerified: true,
            isFeatured: true,
            views: 189,
            saved: 31,
            postedDate: "Yesterday",
            propertyType: "Service Residence",
            floor: "8th Floor",
            furnished: "Semi-Furnished",
            leaseDuration: "6 months min",
            deposit: "1.5 months",
            utilities: "Partial",
            petPolicy: "Not Allowed",
            smoking: "Not Allowed",
            genderPreference: "Female Only",
            roommateCount: "4",
            availableSpots: "1",
            contactPerson: "Sarah Chen",
            contactNumber: "+6016-987 6543",
            whatsappAvailable: true,
        },
        {
            id: 3,
            image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "MIDDLE ROOM",
            price: "RM 750/mo",
            title: "The Grand Subang SS15",
            location: "Subang Jaya, Selangor",
            tags: ["Student", "CookingAllowed", "Pool", "Study", "Furnished"],
            beds: "1",
            baths: "Shared",
            size: "550",
            amenities: ["wifi", "pool", "furnished", "study", "kitchen"],
            rating: 4.7,
            reviews: 32,
            distance: "500m from Taylor's University",
            availableFrom: "Feb 1, 2024",
            isVerified: true,
            isFeatured: true,
            views: 312,
            saved: 56,
            postedDate: "3 days ago",
            propertyType: "Apartment",
            floor: "5th Floor",
            furnished: "Fully Furnished",
            leaseDuration: "12 months",
            deposit: "2 months",
            utilities: "Excluded",
            petPolicy: "Allowed",
            smoking: "Balcony Only",
            genderPreference: "Student Only",
            roommateCount: "2",
            availableSpots: "1",
            contactPerson: "Ahmad Rizal",
            contactNumber: "+6019-876 5432",
            whatsappAvailable: false,
        },
        {
            id: 4,
            image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "STUDIO",
            price: "RM 1,200/mo",
            title: "Mont Kiara Luxury Suites",
            location: "Mont Kiara, Kuala Lumpur",
            tags: ["Luxury", "FullyFurnished", "CityView", "Gym", "Pool"],
            beds: "1",
            baths: "1 Bath",
            size: "850",
            amenities: [
                "wifi",
                "gym",
                "pool",
                "furnished",
                "security",
                "parking",
            ],
            rating: 4.9,
            reviews: 42,
            distance: "2.1 km from International Schools",
            availableFrom: "Immediate",
            isVerified: true,
            isFeatured: false,
            views: 478,
            saved: 89,
            postedDate: "1 week ago",
            propertyType: "Luxury Condominium",
            floor: "21st Floor",
            furnished: "Fully Furnished",
            leaseDuration: "12-24 months",
            deposit: "3 months",
            utilities: "Included",
            petPolicy: "Small Pets Allowed",
            smoking: "Not Allowed",
            genderPreference: "Any",
            roommateCount: "Solo",
            availableSpots: "1",
            contactPerson: "Agent James",
            contactNumber: "+6011-2233 4455",
            whatsappAvailable: true,
        },
        {
            id: 5,
            image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "SHARED ROOM",
            price: "RM 450/mo",
            title: "University Garden Apartments",
            location: "Setapak, Kuala Lumpur",
            tags: ["Student", "Budget", "Shared", "Cooking", "Laundry"],
            beds: "1",
            baths: "Shared",
            size: "350",
            amenities: ["wifi", "laundry", "kitchen", "study"],
            rating: 4.3,
            reviews: 15,
            distance: "Walking distance to TAR University",
            availableFrom: "Jan 20, 2024",
            isVerified: true,
            isFeatured: false,
            views: 156,
            saved: 23,
            postedDate: "5 hours ago",
            propertyType: "Flat",
            floor: "3rd Floor",
            furnished: "Basic Furnished",
            leaseDuration: "6 months min",
            deposit: "1 month",
            utilities: "Included",
            petPolicy: "Not Allowed",
            smoking: "Not Allowed",
            genderPreference: "Male Only",
            roommateCount: "5",
            availableSpots: "2",
            contactPerson: "Raj Kumar",
            contactNumber: "+6013-456 7890",
            whatsappAvailable: true,
        },
        {
            id: 6,
            image: "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "MASTER ROOM",
            price: "RM 950/mo",
            title: "KL Sentral Residences",
            location: "Brickfields, Kuala Lumpur",
            tags: ["CityCenter", "Transport", "Modern", "Security", "Balcony"],
            beds: "1",
            baths: "1 Bath",
            size: "700",
            amenities: ["wifi", "security", "balcony", "ac", "parking"],
            rating: 4.5,
            reviews: 28,
            distance: "Adjacent to KL Sentral Station",
            availableFrom: "Immediate",
            isVerified: true,
            isFeatured: true,
            views: 321,
            saved: 67,
            postedDate: "Today",
            propertyType: "Serviced Apartment",
            floor: "15th Floor",
            furnished: "Fully Furnished",
            leaseDuration: "12 months",
            deposit: "2 months",
            utilities: "Partial",
            petPolicy: "Allowed",
            smoking: "Not Allowed",
            genderPreference: "Professional Only",
            roommateCount: "3",
            availableSpots: "1",
            contactPerson: "Lisa Wong",
            contactNumber: "+6017-3344 5566",
            whatsappAvailable: true,
        },
        {
            id: 7,
            image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "WHOLE UNIT",
            price: "RM 2,500/mo",
            title: "Damansara Heights Villa",
            location: "Damansara Heights, KL",
            tags: ["Luxury", "Private", "Garden", "Pool", "Security"],
            beds: "3",
            baths: "3 Baths",
            size: "1,800",
            amenities: [
                "wifi",
                "pool",
                "garden",
                "security",
                "parking",
                "maid",
            ],
            rating: 4.9,
            reviews: 37,
            distance: "Near international schools",
            availableFrom: "Mar 1, 2024",
            isVerified: true,
            isFeatured: true,
            views: 512,
            saved: 124,
            postedDate: "2 days ago",
            propertyType: "Terrace House",
            floor: "2 Storeys",
            furnished: "Partially Furnished",
            leaseDuration: "24 months",
            deposit: "3 months",
            utilities: "Excluded",
            petPolicy: "Allowed",
            smoking: "Not Allowed",
            genderPreference: "Family",
            roommateCount: "N/A",
            availableSpots: "Whole Unit",
            contactPerson: "Property Agent",
            contactNumber: "+6018-9988 7766",
            whatsappAvailable: true,
        },
        {
            id: 8,
            image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
            type: "SINGLE ROOM",
            price: "RM 550/mo",
            title: "Cyberjaya Lakeview Suites",
            location: "Cyberjaya, Selangor",
            tags: ["TechHub", "Quiet", "LakeView", "Study", "Modern"],
            beds: "1",
            baths: "Shared",
            size: "480",
            amenities: ["wifi", "study", "gym", "pool", "parking"],
            rating: 4.4,
            reviews: 19,
            distance: "Next to Multimedia University",
            availableFrom: "Feb 15, 2024",
            isVerified: true,
            isFeatured: false,
            views: 198,
            saved: 34,
            postedDate: "4 days ago",
            propertyType: "Condominium",
            floor: "10th Floor",
            furnished: "Fully Furnished",
            leaseDuration: "12 months",
            deposit: "1.5 months",
            utilities: "Included",
            petPolicy: "Not Allowed",
            smoking: "Not Allowed",
            genderPreference: "Mixed",
            roommateCount: "4",
            availableSpots: "2",
            contactPerson: "Tech Student",
            contactNumber: "+6014-1122 3344",
            whatsappAvailable: true,
        },
    ];

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
            <Navbar />
            <div className="max-w-7xl mx-auto px-4 py-8">
                {/* Page Header */}
                <div className="mb-8">
                    <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
                        Find your perfect room in Malaysia
                    </h1>
                    <p className="text-gray-600 dark:text-gray-400">
                        Showing {dummyListings.length} verified listings in
                        Kuala Lumpur & Selangor
                    </p>
                </div>

                <SearchFilterBar />

                {/* Grid of Listing Cards */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 mt-8">
                    {dummyListings.map((listing) => (
                        <ListingCard key={listing.id} listing={listing} />
                    ))}
                </div>

                {/* Load More Button */}
                <div className="mt-12 text-center">
                    <button className="px-8 py-3 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl text-gray-700 dark:text-gray-300 font-medium hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
                        Load More Listings
                    </button>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
                        Showing 8 of 1,240+ listings
                    </p>
                </div>
            </div>
        </div>
    );
}
